#' Create a `grViz` specification from a function matrix
#'
#' Given a function matrix created by [function_matrix()], convert it into a text specification
#' that can be passed to [DiagrammeR::grViz()].
#'
#' @param funmat A function matrix generated by [function_matrix()].
#' @param title The name of the graph. Will be displayed as mouseover text.
#'
#' @return A text string.
#'
#' @export
graph_spec_from_matrix <- function(funmat, title = "foodweb") {
  template <- "digraph \"{title}\" {{{graph_data}\n}}"
  graph_data <- character()
  for (caller_name in rownames(funmat)) {
    called_fns <- colnames(funmat)[funmat[caller_name, ] > 0]
    called_fns <- glue::glue("\"{called_fns}()\"")
    # TODO: Do we want an option to include orphan functions in the output?
    if (length(called_fns) > 0) {
      spec <- glue::glue("  \"{caller_name}()\" -> {{ {paste(called_fns, collapse = ', ')} }}")
      graph_data <- paste(graph_data, spec, sep = "\n")
    }
  }
  glue::glue(template)
}
